### ISSUE TITLE
Prepare nginx configuration for D7 site

### ISSUE THREAD

**Issue by rfay** [warmshowers/Warmshowers.org#704]
On the staging server I've upgraded to Perusio's current config. However, it does not have https, and it will have to be tried and proved on staging/dev.

- [x] Make sure that the change for perusio php-fpm problem gets in there (#562)
- [x] Test with https only (not currently configured)
- [x] Verify that the problem with autocomplete access on nginx is resolved, https://github.com/perusio/drupal-with-nginx/issues/226
- [x] Provide HTML "Site is down for upgrade" default page for notification to people during upgrade (if possible) (html from #861) (The code to do this is in apps/drupal/drupal.conf - it has to be uncommented)
- [x] Make and test a warmshowers.org configuration, check it in there. 
- [x] Make a warmshowers_org branch of config in preparation

**Comment by rfay** [comment]
nginx config is checked into a private repository, tracked in /etc/nginx.
