### ISSUE TITLE
D7 Deployment plan

### ISSUE THREAD

**Issue by rfay** [warmshowers/Warmshowers.org#783]
Before deploy day:
- [x] Prepare and test nginx config with SSL per #704
- [x] Prepare and test memcache configuration
- [x] Prepare and test settings.local.php, see #847 
- [x] Prepare and test cron setup
- [x] Announce downtime in advance on site and on Facebook and Twitter
- [x] Update and test the maintenance message
- [x] Prepare a D6 clone site for reference with *very* recent db and files
- [x] Refresh local D6 dev site for reference (warmshowers.dev)
- [x] Prepare drush mailaview scripts and deploy on wsupg.net (See #711)
- [x] Do a dress rehearsal upgrade on staging server
- [x] Install compass on prod server

At deployment time:
- [x] Announce again on Facebook and Twitter
- [x] Make backup of files (rsync update to wsupg.net is good), check git status (On wsupg.net, in files dir, `rsync -avz warmshowers.org:/mnt/wsfiles/ . --exclude=css --exclude=js --exclude=imagecache --exclude="imagefield*"`
- [x] Take site offline "Maintenance mode"
- [x] Truncate sessions table, search_dataset, search_index
- [x] Save database dump
- [x] Check out new nginx code into /etc/nginx
- [x] Configure nginx apps/drupal/drupal.conf to enable 503 maintenance mode
- [x] Install maintenance.html page and test it.
- [x] Checkout site_d7 as codebase
- [x] Run through updb
- [x] Test basic functionality
- [x] Take site out of maintenance mode
- [x] Remove 503 maint code from drupal.conf in nginx (just do git checkout drupal.conf on it)
- [x] Run and resolve security_review issues
- [x] Check mandrill incoming, other items on monitor.thefays.us
- [x] Test anon access to front page
- [x] Place any blocks as necessary, especially highlight blocks
- [x] Test android functionality (iOS will be broken)
- [x] Provide forum technique for people to describe problems - one of the highlighted blocks. Point people to it on FB group.
- [x] Announce it's back up on twitter/fb
- [x] Announce that IOS and Windows Phone apps are broken
- [ ] Re-enable /etc/cron.daily/drupal_cron
- [x] Verify status on New Relic and on icinga
- [x] Set up daily admin emails using drush mailaview
- [x] Turn on basic authentication again on staging server
- [ ] Check to make sure that cron (including queue-list) works the way we want
- [x] Check donation processing
- [x] Spot-check logs

**Comment by rfay** [comment]
Cron config moved into #905
